services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: task_manager_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - task-network
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - task-network

  backend:
    build: ./back-end
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=example
      - MYSQL_DATABASE=task_manager_db
    networks:
      - task-network
    depends_on:
      - db
    
  frontend:
    build: ./front-end
    ports:
      - "3000:3000"
    networks:
      - task-network

volumes:
  db_data:

networks:
  task-network:
